### ISSUE TITLE
Comm error:4 when updating

### ISSUE THREAD

**Issue by wisnij** [SeaPea/ForeCal#2]
Since late last week, ForeCal on my watch hasn't been updating with recent weather data, instead displaying "Comm error:4" when fetching. If I'm reading the Pebble dev documentation right, this means "`APP_MSG_SEND_REJECTED` - The other end rejected the sent data, with a 'nack' reply".  I installed a a watch firmware update recently as well, which may be a factor.  (I've currently got firmware v3.9.2 on a Pebble Classic.)

**Comment by SeaPea** [comment]
Have you tried rebooting both your watch and phone? That error is in a part of the communication stack that my app cannot access.

**Comment by wisnij** [comment]
I did, but it's still happening.

**Comment by SeaPea** [comment]
What version of ForeCall do you have installed? (it's at the bottom of the settings page in the Pebble phone app)
What phone OS are you running and what version of the Pebble phone app do you have? 
Are any other weather watch faces working?

**Comment by wisnij** [comment]
ForeCal v2.10, Android version 4.4.2, Pebble Time app v3.9.1-966-bc5f043.  I tried installing two other watchfaces that display weather, Timely and YWeather, and Timely was able to fetch weather data but YWeather was not.

...and when I switched back to ForeCal after checking the other watch faces, it started working again.  Weird.  Maybe it was changing the faces after rebooting that did it.

**Comment by SeaPea** [comment]
Must have been a glitch in the Pebble comms somewhere. Not much I can do about that.
