### ISSUE TITLE
Weather Not Updating

### ISSUE THREAD

**Issue by clreinki** [SeaPea/ForeCal#3]
Due to the Yahoo Weather API change that went into effect on March 15 2016, weather is no longer updating on this watchface.

As a sidenote, what is the open source license type of ForeCal?

**Comment by SeaPea** [comment]
Yes, I am in the process of switching to OpenWeatherMap as they have a much higher limit on the free API access, but it will take a few days as the free data they provide for forecasts is quite different. 

There is no official license for the code. Use it however you want. It is pretty bad code though. It was my first Pebble app and my first C app in a long long time that grew and grew from the original Pebble weather example.

**Comment by clreinki** [comment]
Cool - just a heads up, I've started a fork of the watchface that utilizes Wunderground's API.  It requires that each user have their own API key though.  The fork is located here if you want to see what I did: github.com/clreinki/forecal

**Comment by SeaPea** [comment]
Just released V3.0 with OpenWeatherMap and the offline Clay config framework.

Be aware with the fork, unless you also get the Clay config updates from V3.0, the previous config HTML was hosted on my web server and may disappear at some point.
