### ISSUE TITLE
Weather not showing

### ISSUE THREAD

**Issue by UnknownAudi00o** [SeaPea/ForeCal#4]
As a few days ago, the weather area is blank. Not sure exactly what is going on.

**Comment by SeaPea** [comment]
I have been experiencing this off and on recently too, but it has always been going back to normal an hour or two later. I keep missing being at a computer to check it out when it happens but I suspect an issue with the weather data service. Will try and investigate when it happens to me again.

**Comment by SeaPea** [comment]
This should be fixed in V3.4, which has just been released.
